# yaml-language-server: $schema=https://raw.githubusercontent.com/XXXDelirious/taskgraph/main/schema/taskfile.json

version: '3'

vars:
  GREETING: Hello, world!

tasks:
  default:
    desc: Print a greeting message
    cmds:
      - echo "{{.GREETING}}"
    silent: true
